// Hand-authored source catalog for Petals.
//
// This file holds every field that is a matter of horticultural fact or florist
// judgement. The only things NOT here are `imageUrl`, `imageAttribution` and
// `imageHex` -- those are filled in by scripts/build-data.mjs, which queries the
// Wikimedia Commons API, verifies the URL returns 200, and samples the photo for
// its dominant petal colour. Entries whose image cannot be verified are dropped.
//
// Field notes:
//   form      ruffled | spiky | star | bell | cluster | single | globe
//   scale     focal | secondary | filler
//   scent     none | light | sweet | spicy | green
//   seasons   spring | summer | fall | winter   (peak availability at a florist)
//   priceTier 1 = supermarket-cheap, 2 = mid, 3 = splurge / specialty order
//   colors[]  the orderable colour range for the variety, not the photo
//   query     the Commons search string; keep it botanical, it ranks far better

export const FLOWERS = [
  {
    id: 'garden-rose',
    commonName: 'Garden Rose',
    scientificName: 'Rosa × hybrida',
    query: 'Rosa garden rose flower closeup',
    colors: [
      { name: 'blush', hex: '#EFC3C6' }, { name: 'cream', hex: '#F5EAD6' },
      { name: 'coral', hex: '#F08874' }, { name: 'crimson', hex: '#A3172B' },
      { name: 'butter', hex: '#F4DE9C' },
    ],
    form: 'ruffled', scale: 'focal', scent: 'sweet',
    seasons: ['spring', 'summer', 'fall'], priceTier: 3,
    vibeTags: ['romantic', 'classic', 'lush', 'english-garden'],
    blurb: 'The one everyone pictures, but the garden varieties open into a hundred soft petals instead of the tight cone you get at a corner shop.',
  },
  {
    id: 'peony',
    commonName: 'Peony',
    scientificName: 'Paeonia lactiflora',
    query: 'Paeonia lactiflora flower',
    colors: [
      { name: 'blush', hex: '#F3C4CE' }, { name: 'white', hex: '#F7F2EA' },
      { name: 'coral', hex: '#F2856E' }, { name: 'fuchsia', hex: '#C6407E' },
    ],
    form: 'ruffled', scale: 'focal', scent: 'sweet',
    seasons: ['spring', 'summer'], priceTier: 3,
    vibeTags: ['romantic', 'lush', 'soft', 'luxurious'],
    blurb: 'Arrives as a hard ball and opens over three days into something absurd. Season is short and everyone wants them, which is most of the price.',
  },
  {
    id: 'dahlia',
    commonName: 'Dahlia',
    scientificName: 'Dahlia pinnata',
    query: 'Dahlia pinnata flower',
    colors: [
      { name: 'burgundy', hex: '#6E1B2E' }, { name: 'peach', hex: '#F6B48D' },
      { name: 'white', hex: '#F4F0E8' }, { name: 'plum', hex: '#7A3B6B' },
      { name: 'sunset orange', hex: '#E8712C' },
    ],
    form: 'globe', scale: 'focal', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 2,
    vibeTags: ['geometric', 'dramatic', 'late-summer', 'painterly'],
    blurb: 'Petals laid out in a spiral so precise it looks engineered. Comes in everything from a golf ball to a dinner plate.',
  },
  {
    id: 'ranunculus',
    commonName: 'Ranunculus',
    scientificName: 'Ranunculus asiaticus',
    query: 'Ranunculus asiaticus flower',
    colors: [
      { name: 'cream', hex: '#F6EDD8' }, { name: 'blush', hex: '#F2C7C0' },
      { name: 'butter', hex: '#F7D97A' }, { name: 'raspberry', hex: '#C23B5E' },
      { name: 'cafe au lait', hex: '#DBB89C' },
    ],
    form: 'ruffled', scale: 'focal', scent: 'light',
    seasons: ['spring'], priceTier: 2,
    vibeTags: ['delicate', 'romantic', 'tissue-paper', 'soft'],
    blurb: 'Layer after layer of petals as thin as tissue, on a stem that curves wherever it likes. The florist favourite that never photographs as well as it looks.',
  },
  {
    id: 'tulip',
    commonName: 'Tulip',
    scientificName: 'Tulipa gesneriana',
    query: 'Tulipa gesneriana flower',
    colors: [
      { name: 'white', hex: '#F6F1E7' }, { name: 'pink', hex: '#EC93B0' },
      { name: 'red', hex: '#C1272D' }, { name: 'yellow', hex: '#F4C842' },
      { name: 'purple', hex: '#6E4B8E' },
    ],
    form: 'bell', scale: 'focal', scent: 'light',
    seasons: ['spring', 'winter'], priceTier: 1,
    vibeTags: ['clean', 'modern', 'simple', 'cheerful'],
    blurb: 'Keeps growing after you cut it and leans toward the nearest window, so an arrangement rearranges itself overnight.',
  },
  {
    id: 'oriental-lily',
    commonName: 'Oriental Lily',
    scientificName: 'Lilium orientalis',
    query: 'Lilium orientalis flower',
    colors: [
      { name: 'white', hex: '#F8F4EC' }, { name: 'pink', hex: '#E77FA0' },
      { name: 'magenta', hex: '#B93A72' },
    ],
    form: 'star', scale: 'focal', scent: 'sweet',
    seasons: ['summer', 'fall'], priceTier: 2,
    vibeTags: ['dramatic', 'perfumed', 'formal', 'statement'],
    blurb: 'The scent fills a room within an hour, which people either love or find is a bit much. Pollen stains, so florists pinch the anthers off.',
  },
  {
    id: 'sunflower',
    commonName: 'Sunflower',
    scientificName: 'Helianthus annuus',
    query: 'Helianthus annuus flower head',
    colors: [
      { name: 'gold', hex: '#EFB01F' }, { name: 'bronze', hex: '#9C5B23' },
      { name: 'lemon', hex: '#F2D96A' },
    ],
    form: 'single', scale: 'focal', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 1,
    vibeTags: ['cheerful', 'rustic', 'bold', 'farmhouse'],
    blurb: 'A single face big enough to carry a whole jar on its own. Reads as friendly rather than romantic, which is sometimes exactly right.',
  },
  {
    id: 'hydrangea',
    commonName: 'Hydrangea',
    scientificName: 'Hydrangea macrophylla',
    query: 'Hydrangea macrophylla inflorescence',
    colors: [
      { name: 'antique blue', hex: '#8FA8C8' }, { name: 'white', hex: '#EFEDE2' },
      { name: 'blush', hex: '#E7B8C2' }, { name: 'sage green', hex: '#AFBE94' },
    ],
    form: 'cluster', scale: 'focal', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 2,
    vibeTags: ['abundant', 'soft', 'coastal', 'vintage'],
    blurb: 'One stem fills a third of a vase. The colour depends on soil pH, which is why the blue ones look faintly unreal.',
  },
  {
    id: 'king-protea',
    commonName: 'King Protea',
    scientificName: 'Protea cynaroides',
    query: 'Protea cynaroides',
    colors: [
      { name: 'dusty pink', hex: '#D98C97' }, { name: 'cream', hex: '#EADFC6' },
      { name: 'rust', hex: '#B05B34' },
    ],
    form: 'spiky', scale: 'focal', scent: 'none',
    seasons: ['fall', 'winter'], priceTier: 3,
    vibeTags: ['architectural', 'sculptural', 'bold', 'modern'],
    blurb: 'The size of a grapefruit and closer to an artichoke than a rose. Dries beautifully, so it outlasts everything else in the vase by months.',
  },
  {
    id: 'anemone',
    commonName: 'Anemone',
    scientificName: 'Anemone coronaria',
    query: 'Anemone coronaria flower',
    colors: [
      { name: 'white', hex: '#F4F1E9' }, { name: 'deep purple', hex: '#4B3268' },
      { name: 'red', hex: '#B01C2E' }, { name: 'blush', hex: '#F0C2CB' },
    ],
    form: 'single', scale: 'focal', scent: 'none',
    seasons: ['winter', 'spring'], priceTier: 2,
    vibeTags: ['graphic', 'moody', 'high-contrast', 'modern'],
    blurb: 'A jet-black centre against a pale petal — the highest-contrast thing you can put in a bouquet without it looking loud.',
  },
  {
    id: 'gerbera',
    commonName: 'Gerbera Daisy',
    scientificName: 'Gerbera jamesonii',
    query: 'Gerbera jamesonii flower',
    colors: [
      { name: 'hot pink', hex: '#E14C8A' }, { name: 'orange', hex: '#F0812B' },
      { name: 'yellow', hex: '#F5C518' }, { name: 'white', hex: '#F5F2EA' },
    ],
    form: 'single', scale: 'focal', scent: 'none',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 1,
    vibeTags: ['cheerful', 'graphic', 'playful', 'bold'],
    blurb: 'A perfect flat circle of colour. Cheap, available year round, and slightly divisive — some people find it a bit cartoonish.',
  },
  {
    id: 'chrysanthemum',
    commonName: 'Chrysanthemum',
    scientificName: 'Chrysanthemum morifolium',
    query: 'Chrysanthemum morifolium flower',
    colors: [
      { name: 'bronze', hex: '#B4703A' }, { name: 'white', hex: '#F3F0E6' },
      { name: 'butter', hex: '#F0D780' }, { name: 'plum', hex: '#78405F' },
    ],
    form: 'globe', scale: 'focal', scent: 'green',
    seasons: ['fall'], priceTier: 1,
    vibeTags: ['autumnal', 'long-lasting', 'traditional', 'earthy'],
    blurb: 'Unfashionable for a decade and quietly back, especially the big spidery ones. Lasts nearly three weeks in water.',
  },
  {
    id: 'amaryllis',
    commonName: 'Amaryllis',
    scientificName: 'Hippeastrum hybridum',
    query: 'Hippeastrum flower',
    colors: [
      { name: 'scarlet', hex: '#B71C24' }, { name: 'white', hex: '#F6F2E8' },
      { name: 'salmon', hex: '#EE9377' },
    ],
    form: 'bell', scale: 'focal', scent: 'light',
    seasons: ['winter'], priceTier: 3,
    vibeTags: ['dramatic', 'festive', 'statement', 'architectural'],
    blurb: 'Four trumpets on one hollow stem, each the width of your hand. Florists stuff the stem with a bamboo cane so it can hold its own head up.',
  },
  {
    id: 'calla-lily',
    commonName: 'Calla Lily',
    scientificName: 'Zantedeschia aethiopica',
    query: 'Zantedeschia aethiopica flower',
    colors: [
      { name: 'ivory', hex: '#F4EFE1' }, { name: 'deep plum', hex: '#4A2038' },
      { name: 'mango', hex: '#EFA13C' },
    ],
    form: 'bell', scale: 'focal', scent: 'light',
    seasons: ['spring', 'summer'], priceTier: 3,
    vibeTags: ['minimal', 'sculptural', 'modern', 'elegant'],
    blurb: 'One clean curve and nothing else. Three of them in a tall vase is a complete arrangement — anything more starts to fight it.',
  },
  {
    id: 'bearded-iris',
    commonName: 'Bearded Iris',
    scientificName: 'Iris germanica',
    query: 'Iris germanica flower',
    colors: [
      { name: 'violet', hex: '#6A4A9C' }, { name: 'white', hex: '#F3F0E7' },
      { name: 'bronze', hex: '#9C6B2F' }, { name: 'sky', hex: '#9FB4DA' },
    ],
    form: 'star', scale: 'focal', scent: 'light',
    seasons: ['spring'], priceTier: 2,
    vibeTags: ['painterly', 'antique', 'velvety', 'dramatic'],
    blurb: 'Falls like velvet with a fuzzy stripe down the middle. Lasts about three days, which is the price of looking like a Van Gogh.',
  },
  {
    id: 'lisianthus',
    commonName: 'Lisianthus',
    scientificName: 'Eustoma grandiflorum',
    query: 'Eustoma grandiflorum flower',
    colors: [
      { name: 'white', hex: '#F5F1E6' }, { name: 'lavender', hex: '#B5A0CE' },
      { name: 'blush', hex: '#EFC5CB' }, { name: 'deep purple', hex: '#583B7C' },
    ],
    form: 'ruffled', scale: 'focal', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 2,
    vibeTags: ['romantic', 'soft', 'rose-alternative', 'refined'],
    blurb: 'Reads as a rose from across the room and costs a third as much. Each stem carries several blooms plus buds, so it keeps opening.',
  },
  {
    id: 'iceland-poppy',
    commonName: 'Iceland Poppy',
    scientificName: 'Papaver nudicaule',
    query: 'Papaver nudicaule flower',
    colors: [
      { name: 'apricot', hex: '#F4A96A' }, { name: 'white', hex: '#F7F3E9' },
      { name: 'coral', hex: '#F27059' }, { name: 'lemon', hex: '#F6D65E' },
    ],
    form: 'single', scale: 'focal', scent: 'none',
    seasons: ['spring'], priceTier: 2,
    vibeTags: ['delicate', 'airy', 'whimsical', 'crepe-paper'],
    blurb: 'Crumpled like it was folded in a pocket, on a hairy stem that wanders. Florists sear the cut end so it doesn\'t bleed out.',
  },
  {
    id: 'gladiolus',
    commonName: 'Gladiolus',
    scientificName: 'Gladiolus hortulanus',
    query: 'Gladiolus flower spike',
    colors: [
      { name: 'white', hex: '#F5F1E8' }, { name: 'coral', hex: '#F0806D' },
      { name: 'magenta', hex: '#C13C7C' }, { name: 'green', hex: '#B9C293' },
    ],
    form: 'spiky', scale: 'focal', scent: 'none',
    seasons: ['summer'], priceTier: 1,
    vibeTags: ['tall', 'traditional', 'vertical', 'grand'],
    blurb: 'A metre of flowers opening bottom to top over a week. Divisive — some read it as grand, some as funeral parlour.',
  },
  {
    id: 'delphinium',
    commonName: 'Delphinium',
    scientificName: 'Delphinium elatum',
    query: 'Delphinium elatum flower',
    colors: [
      { name: 'true blue', hex: '#3B62A8' }, { name: 'white', hex: '#F4F1E8' },
      { name: 'lilac', hex: '#A695C6' },
    ],
    form: 'spiky', scale: 'focal', scent: 'none',
    seasons: ['summer'], priceTier: 2,
    vibeTags: ['english-garden', 'vertical', 'cottage', 'airy'],
    blurb: 'One of the very few genuinely blue flowers, which is why it costs what it does. Gives an arrangement height without weight.',
  },
  {
    id: 'snapdragon',
    commonName: 'Snapdragon',
    scientificName: 'Antirrhinum majus',
    query: 'Antirrhinum majus flower',
    colors: [
      { name: 'butter', hex: '#F5D77E' }, { name: 'blush', hex: '#F0BFC4' },
      { name: 'burgundy', hex: '#7C2438' }, { name: 'white', hex: '#F5F2E9' },
    ],
    form: 'spiky', scale: 'secondary', scent: 'light',
    seasons: ['spring', 'summer', 'fall'], priceTier: 1,
    vibeTags: ['cottage', 'playful', 'vertical', 'nostalgic'],
    blurb: 'Pinch the side of a bloom and it opens like a mouth. The tips curve upward in the vase no matter which way you set them.',
  },
  {
    id: 'stock',
    commonName: 'Stock',
    scientificName: 'Matthiola incana',
    query: 'Matthiola incana flower',
    colors: [
      { name: 'cream', hex: '#F3EBD8' }, { name: 'lavender', hex: '#B3A2CC' },
      { name: 'blush', hex: '#EEC0C7' }, { name: 'plum', hex: '#6E3E70' },
    ],
    form: 'spiky', scale: 'secondary', scent: 'spicy',
    seasons: ['spring', 'winter'], priceTier: 1,
    vibeTags: ['perfumed', 'cottage', 'old-fashioned', 'soft'],
    blurb: 'Smells like cloves and cinnamon from across the room. Cheap, generous, and does most of the scent work in a spring bouquet.',
  },
  {
    id: 'larkspur',
    commonName: 'Larkspur',
    scientificName: 'Consolida ajacis',
    query: 'Consolida ajacis flower',
    colors: [
      { name: 'periwinkle', hex: '#8C9BD6' }, { name: 'white', hex: '#F4F1E7' },
      { name: 'rose', hex: '#DE93AE' },
    ],
    form: 'spiky', scale: 'secondary', scent: 'none',
    seasons: ['summer'], priceTier: 1,
    vibeTags: ['cottage', 'airy', 'wildflower', 'vertical'],
    blurb: 'Delphinium\'s looser cousin — the same blue spires but thinner, so it scatters through a bouquet instead of anchoring it.',
  },
  {
    id: 'foxglove',
    commonName: 'Foxglove',
    scientificName: 'Digitalis purpurea',
    query: 'Digitalis purpurea flower',
    colors: [
      { name: 'mauve', hex: '#C08BB4' }, { name: 'white', hex: '#F4F0E6' },
      { name: 'apricot', hex: '#EBB183' },
    ],
    form: 'bell', scale: 'focal', scent: 'none',
    seasons: ['summer'], priceTier: 2,
    vibeTags: ['english-garden', 'wild', 'vertical', 'storybook'],
    blurb: 'A one-sided tower of speckled thimbles. Genuinely poisonous, so it belongs in a vase and nowhere near a kitchen counter.',
  },
  {
    id: 'lupine',
    commonName: 'Lupine',
    scientificName: 'Lupinus polyphyllus',
    query: 'Lupinus polyphyllus flower',
    colors: [
      { name: 'violet', hex: '#6C55A4' }, { name: 'rose', hex: '#DD87A6' },
      { name: 'butter', hex: '#EFD98A' },
    ],
    form: 'spiky', scale: 'focal', scent: 'light',
    seasons: ['spring', 'summer'], priceTier: 2,
    vibeTags: ['wildflower', 'vertical', 'meadow', 'bold'],
    blurb: 'A dense cone of pea-shaped flowers stacked in tiers. Reads as meadow rather than florist, even in a formal vase.',
  },
  {
    id: 'sweet-pea',
    commonName: 'Sweet Pea',
    scientificName: 'Lathyrus odoratus',
    query: 'Lathyrus odoratus flower',
    colors: [
      { name: 'blush', hex: '#F2C6CE' }, { name: 'cream', hex: '#F6EFDE' },
      { name: 'lilac', hex: '#B6A3D2' }, { name: 'raspberry', hex: '#C64B76' },
    ],
    form: 'ruffled', scale: 'secondary', scent: 'sweet',
    seasons: ['spring'], priceTier: 2,
    vibeTags: ['nostalgic', 'perfumed', 'delicate', 'ruffled'],
    blurb: 'The best-smelling thing in the flower market and the shortest-lived — four days if you are lucky. Worth it anyway.',
  },
  {
    id: 'freesia',
    commonName: 'Freesia',
    scientificName: 'Freesia refracta',
    query: 'Freesia refracta flower',
    colors: [
      { name: 'white', hex: '#F6F2E7' }, { name: 'butter', hex: '#F4D982' },
      { name: 'coral', hex: '#EE8B72' }, { name: 'lilac', hex: '#AC9BCB' },
    ],
    form: 'bell', scale: 'secondary', scent: 'sweet',
    seasons: ['winter', 'spring'], priceTier: 2,
    vibeTags: ['perfumed', 'clean', 'fresh', 'delicate'],
    blurb: 'Blooms march along one side of an arched stem and open in sequence. The scent is the citrus-and-honey one used in half of all soap.',
  },
  {
    id: 'carnation',
    commonName: 'Carnation',
    scientificName: 'Dianthus caryophyllus',
    query: 'Dianthus caryophyllus flower',
    colors: [
      { name: 'antique mauve', hex: '#C39BAA' }, { name: 'cream', hex: '#F4ECDA' },
      { name: 'burgundy', hex: '#6F1F32' }, { name: 'peach', hex: '#F3B48E' },
    ],
    form: 'ruffled', scale: 'secondary', scent: 'spicy',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 1,
    vibeTags: ['retro', 'textural', 'long-lasting', 'underrated'],
    blurb: 'Written off for thirty years and now everywhere again, mostly in the odd antique shades. Lasts two weeks and smells faintly of cloves.',
  },
  {
    id: 'alstroemeria',
    commonName: 'Alstroemeria',
    scientificName: 'Alstroemeria aurea',
    query: 'Alstroemeria flower',
    colors: [
      { name: 'peach', hex: '#F3B084' }, { name: 'white', hex: '#F4F1E7' },
      { name: 'raspberry', hex: '#C24C74' }, { name: 'butter', hex: '#F1D97F' },
    ],
    form: 'star', scale: 'secondary', scent: 'none',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 1,
    vibeTags: ['long-lasting', 'speckled', 'workhorse', 'cheerful'],
    blurb: 'Freckled throat, six blooms per stem, and it will outlast every other flower in the vase. The reliable middle of most mixed bunches.',
  },
  {
    id: 'daffodil',
    commonName: 'Daffodil',
    scientificName: 'Narcissus pseudonarcissus',
    query: 'Narcissus pseudonarcissus flower',
    colors: [
      { name: 'yellow', hex: '#F3C723' }, { name: 'white', hex: '#F6F2E6' },
      { name: 'apricot', hex: '#F0A868' },
    ],
    form: 'star', scale: 'secondary', scent: 'sweet',
    seasons: ['spring'], priceTier: 1,
    vibeTags: ['cheerful', 'first-of-spring', 'simple', 'nostalgic'],
    blurb: 'The sap poisons other flowers, so it needs to sit in its own water overnight before joining a mixed arrangement.',
  },
  {
    id: 'hyacinth',
    commonName: 'Hyacinth',
    scientificName: 'Hyacinthus orientalis',
    query: 'Hyacinthus orientalis flower',
    colors: [
      { name: 'white', hex: '#F5F2E8' }, { name: 'periwinkle', hex: '#8E9BD3' },
      { name: 'blush', hex: '#EFBFCB' }, { name: 'grape', hex: '#5D3C86' },
    ],
    form: 'cluster', scale: 'secondary', scent: 'sweet',
    seasons: ['winter', 'spring'], priceTier: 1,
    vibeTags: ['perfumed', 'dense', 'waxy', 'spring'],
    blurb: 'A fat column of waxy stars on a stem that is basically all water. The scent is enormous for the size of the flower.',
  },
  {
    id: 'grape-hyacinth',
    commonName: 'Grape Hyacinth',
    scientificName: 'Muscari armeniacum',
    query: 'Muscari armeniacum flower',
    colors: [
      { name: 'cobalt', hex: '#3C4E9E' }, { name: 'white', hex: '#F2EFE6' },
      { name: 'pale blue', hex: '#A7BADD' },
    ],
    form: 'cluster', scale: 'secondary', scent: 'light',
    seasons: ['spring'], priceTier: 2,
    vibeTags: ['tiny', 'jewel-like', 'wild', 'blue'],
    blurb: 'Barely fifteen centimetres tall and the most saturated blue in the market. Used in tight clusters where the eye needs somewhere to land.',
  },
  {
    id: 'lily-of-the-valley',
    commonName: 'Lily of the Valley',
    scientificName: 'Convallaria majalis',
    query: 'Convallaria majalis flower',
    colors: [{ name: 'white', hex: '#F6F3EA' }],
    form: 'bell', scale: 'secondary', scent: 'sweet',
    seasons: ['spring'], priceTier: 3,
    vibeTags: ['bridal', 'delicate', 'perfumed', 'heirloom'],
    blurb: 'Tiny nodding bells with a scent completely out of proportion to their size. Priced like a luxury because the season is three weeks long.',
  },
  {
    id: 'cosmos',
    commonName: 'Cosmos',
    scientificName: 'Cosmos bipinnatus',
    query: 'Cosmos bipinnatus flower',
    colors: [
      { name: 'white', hex: '#F5F2E9' }, { name: 'blush', hex: '#F0BFCD' },
      { name: 'magenta', hex: '#C6407F' },
    ],
    form: 'single', scale: 'secondary', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 1,
    vibeTags: ['airy', 'wildflower', 'movement', 'delicate'],
    blurb: 'A flat disc of petals on a wire-thin stem, so it floats above everything else and moves when you walk past.',
  },
  {
    id: 'zinnia',
    commonName: 'Zinnia',
    scientificName: 'Zinnia elegans',
    query: 'Zinnia elegans flower',
    colors: [
      { name: 'coral', hex: '#F0705C' }, { name: 'lime', hex: '#C3CE72' },
      { name: 'magenta', hex: '#CE3A78' }, { name: 'butter', hex: '#F3D368' },
    ],
    form: 'globe', scale: 'secondary', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 1,
    vibeTags: ['punchy', 'summer', 'saturated', 'cutting-garden'],
    blurb: 'The colours are frankly unsubtle, which is the point. Straight from a cutting garden rather than a wholesaler.',
  },
  {
    id: 'marigold',
    commonName: 'Marigold',
    scientificName: 'Tagetes erecta',
    query: 'Tagetes erecta flower',
    colors: [
      { name: 'saffron', hex: '#EE9C1C' }, { name: 'marigold gold', hex: '#F2B627' },
      { name: 'rust', hex: '#B5551F' },
    ],
    form: 'globe', scale: 'secondary', scent: 'spicy',
    seasons: ['summer', 'fall'], priceTier: 1,
    vibeTags: ['warm', 'festival', 'dense', 'earthy'],
    blurb: 'A tight ball of ruffles in a gold that borders on radioactive. The foliage smells sharp and green when you handle it.',
  },
  {
    id: 'scabiosa',
    commonName: 'Scabiosa',
    scientificName: 'Scabiosa caucasica',
    query: 'Scabiosa caucasica flower',
    colors: [
      { name: 'lavender', hex: '#AFA0CF' }, { name: 'cream', hex: '#F2EBD9' },
      { name: 'burgundy', hex: '#5E2033' },
    ],
    form: 'globe', scale: 'secondary', scent: 'light',
    seasons: ['summer', 'fall'], priceTier: 2,
    vibeTags: ['airy', 'pincushion', 'movement', 'meadow'],
    blurb: 'A domed pincushion on a stem thin enough to nod. The seed heads left behind are arguably better than the flower.',
  },
  {
    id: 'nigella',
    commonName: 'Love-in-a-Mist',
    scientificName: 'Nigella damascena',
    query: 'Nigella damascena flower',
    colors: [
      { name: 'sky blue', hex: '#8FAAD8' }, { name: 'white', hex: '#F3F0E7' },
      { name: 'plum', hex: '#7A5288' },
    ],
    form: 'star', scale: 'secondary', scent: 'green',
    seasons: ['spring', 'summer'], priceTier: 2,
    vibeTags: ['whimsical', 'airy', 'feathery', 'cottage'],
    blurb: 'Sits inside a haze of thread-fine foliage, which is where the name comes from. Adds fog to a bouquet rather than colour.',
  },
  {
    id: 'cornflower',
    commonName: 'Cornflower',
    scientificName: 'Centaurea cyanus',
    query: 'Centaurea cyanus flower',
    colors: [
      { name: 'cornflower blue', hex: '#4A6BC0' }, { name: 'white', hex: '#F3F0E6' },
      { name: 'mauve', hex: '#B08CBD' },
    ],
    form: 'globe', scale: 'secondary', scent: 'light',
    seasons: ['spring', 'summer'], priceTier: 1,
    vibeTags: ['wildflower', 'blue', 'meadow', 'simple'],
    blurb: 'A fringed blue button on a grey-green stem. One of the few blues that costs almost nothing.',
  },
  {
    id: 'sweet-william',
    commonName: 'Sweet William',
    scientificName: 'Dianthus barbatus',
    query: 'Dianthus barbatus flower',
    colors: [
      { name: 'crimson', hex: '#A62139' }, { name: 'blush', hex: '#EFB9C4' },
      { name: 'white', hex: '#F4F1E8' },
    ],
    form: 'cluster', scale: 'secondary', scent: 'spicy',
    seasons: ['spring', 'summer'], priceTier: 1,
    vibeTags: ['cottage', 'dense', 'nostalgic', 'textural'],
    blurb: 'Flat-topped clusters of small fringed flowers, often two-toned with a pale eye. Reads as texture from a distance.',
  },
  {
    id: 'yarrow',
    commonName: 'Yarrow',
    scientificName: 'Achillea millefolium',
    query: 'Achillea millefolium flower',
    colors: [
      { name: 'mustard', hex: '#D9A72C' }, { name: 'cream', hex: '#F0E7CF' },
      { name: 'dusty rose', hex: '#CE8E92' },
    ],
    form: 'cluster', scale: 'secondary', scent: 'green',
    seasons: ['summer', 'fall'], priceTier: 1,
    vibeTags: ['meadow', 'flat-topped', 'dried', 'earthy'],
    blurb: 'Flat plates of hundreds of tiny flowers on a ferny stem. Dries in place without dropping, so it just quietly stays.',
  },
  {
    id: 'echinacea',
    commonName: 'Coneflower',
    scientificName: 'Echinacea purpurea',
    query: 'Echinacea purpurea flower',
    colors: [
      { name: 'dusty pink', hex: '#D083A4' }, { name: 'white', hex: '#F2EFE5' },
      { name: 'burnt orange', hex: '#D96A2C' },
    ],
    form: 'single', scale: 'secondary', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 1,
    vibeTags: ['prairie', 'structural', 'meadow', 'copper-centre'],
    blurb: 'Petals sweep back off a bristly copper cone, so it reads as a shuttlecock more than a daisy.',
  },
  {
    id: 'rudbeckia',
    commonName: 'Black-Eyed Susan',
    scientificName: 'Rudbeckia hirta',
    query: 'Rudbeckia hirta flower',
    colors: [
      { name: 'gold', hex: '#EDB020' }, { name: 'mahogany', hex: '#8C3A1E' },
    ],
    form: 'single', scale: 'secondary', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 1,
    vibeTags: ['prairie', 'warm', 'rustic', 'high-contrast'],
    blurb: 'Gold petals around a near-black dome. The cheapest way to get real contrast into a warm arrangement.',
  },
  {
    id: 'aster',
    commonName: 'Aster',
    scientificName: 'Symphyotrichum novi-belgii',
    query: 'Symphyotrichum novi-belgii flower',
    colors: [
      { name: 'violet', hex: '#7B63B4' }, { name: 'white', hex: '#F3F0E7' },
      { name: 'rose', hex: '#DB8AA9' },
    ],
    form: 'single', scale: 'secondary', scent: 'none',
    seasons: ['fall'], priceTier: 1,
    vibeTags: ['autumnal', 'sprayed', 'meadow', 'small'],
    blurb: 'Dozens of small daisies on one branching stem, arriving right as everything else in the garden gives up.',
  },
  {
    id: 'astrantia',
    commonName: 'Astrantia',
    scientificName: 'Astrantia major',
    query: 'Astrantia major flower',
    colors: [
      { name: 'silver-green', hex: '#D2D5BE' }, { name: 'dusty rose', hex: '#C98E9C' },
      { name: 'wine', hex: '#7A2B3C' },
    ],
    form: 'star', scale: 'secondary', scent: 'green',
    seasons: ['summer'], priceTier: 2,
    vibeTags: ['papery', 'antique', 'textural', 'subtle'],
    blurb: 'A pincushion sitting inside a papery collar of pointed bracts. Looks like something pressed in a book a century ago.',
  },
  {
    id: 'allium',
    commonName: 'Allium',
    scientificName: 'Allium giganteum',
    query: 'Allium giganteum flower',
    colors: [
      { name: 'violet', hex: '#7A5AA8' }, { name: 'white', hex: '#F2EFE6' },
    ],
    form: 'globe', scale: 'focal', scent: 'spicy',
    seasons: ['spring', 'summer'], priceTier: 2,
    vibeTags: ['geometric', 'architectural', 'modern', 'sculptural'],
    blurb: 'A perfect sphere of hundreds of tiny stars on a bare stem. Faintly oniony up close, because it is one.',
  },
  {
    id: 'craspedia',
    commonName: 'Billy Buttons',
    // Sold by florists as Craspedia globosa; the accepted botanical name (and
    // the one Commons files it under) is Pycnosorus globosus.
    scientificName: 'Pycnosorus globosus',
    query: 'Pycnosorus globosus',
    colors: [{ name: 'gold', hex: '#EFC02A' }],
    form: 'globe', scale: 'secondary', scent: 'none',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 2,
    vibeTags: ['graphic', 'playful', 'modern', 'dried'],
    blurb: 'A yellow drumstick on a leafless stem. Completely dries out and stays exactly the same, indefinitely.',
  },
  {
    id: 'veronica',
    commonName: 'Veronica',
    scientificName: 'Veronica spicata',
    query: 'Veronica spicata flower',
    colors: [
      { name: 'violet', hex: '#7059A6' }, { name: 'white', hex: '#F3F0E7' },
      { name: 'pink', hex: '#DE8FAF' },
    ],
    form: 'spiky', scale: 'secondary', scent: 'none',
    seasons: ['summer'], priceTier: 1,
    vibeTags: ['slender', 'vertical', 'meadow', 'fine'],
    blurb: 'Thin tapering spires that curve at the tip. Gives a bouquet vertical lines without the weight of a delphinium.',
  },
  {
    id: 'celosia',
    commonName: 'Celosia',
    scientificName: 'Celosia argentea',
    query: 'Celosia argentea flower',
    colors: [
      { name: 'magenta', hex: '#C0357B' }, { name: 'coral', hex: '#EE6F4C' },
      { name: 'chartreuse', hex: '#C0CB5B' }, { name: 'burgundy', hex: '#75203A' },
    ],
    form: 'spiky', scale: 'focal', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 2,
    vibeTags: ['textural', 'velvet', 'strange', 'saturated'],
    blurb: 'Either a velvet brain or a flame, depending on the type. The texture is genuinely unlike anything else available.',
  },
  {
    id: 'gomphrena',
    commonName: 'Globe Amaranth',
    scientificName: 'Gomphrena globosa',
    query: 'Gomphrena globosa flower',
    colors: [
      { name: 'magenta', hex: '#C0468C' }, { name: 'white', hex: '#F2EFE6' },
      { name: 'lilac', hex: '#B79AC9' },
    ],
    form: 'globe', scale: 'secondary', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 1,
    vibeTags: ['clover-like', 'papery', 'small', 'dried'],
    blurb: 'A papery clover-shaped button that feels dry to the touch even when fresh. Scatters small points of colour through a mix.',
  },
  {
    id: 'anthurium',
    commonName: 'Anthurium',
    scientificName: 'Anthurium andraeanum',
    query: 'Anthurium andraeanum flower',
    colors: [
      { name: 'lacquer red', hex: '#B81F2C' }, { name: 'white', hex: '#F3F0E6' },
      { name: 'chocolate', hex: '#5A3126' }, { name: 'blush', hex: '#EDB6BE' },
    ],
    form: 'single', scale: 'focal', scent: 'none',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 3,
    vibeTags: ['tropical', 'lacquered', 'modern', 'graphic'],
    blurb: 'A single flat heart that looks wet and plastic even when it is not. Lasts three weeks and reads entirely as design object.',
  },
  {
    id: 'bird-of-paradise',
    commonName: 'Bird of Paradise',
    scientificName: 'Strelitzia reginae',
    query: 'Strelitzia reginae flower',
    colors: [
      { name: 'orange', hex: '#EE7B18' }, { name: 'royal blue', hex: '#2A50A0' },
    ],
    form: 'spiky', scale: 'focal', scent: 'none',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 3,
    vibeTags: ['tropical', 'sculptural', 'bold', 'exotic'],
    blurb: 'An orange crest and a blue tongue emerging sideways from a beak-shaped bract. Impossible to make look soft.',
  },
  {
    id: 'banksia',
    commonName: 'Banksia',
    scientificName: 'Banksia coccinea',
    query: 'Banksia coccinea flower',
    colors: [
      { name: 'scarlet', hex: '#C33A26' }, { name: 'ochre', hex: '#C98D2C' },
      { name: 'rust', hex: '#9E5330' },
    ],
    form: 'spiky', scale: 'focal', scent: 'none',
    seasons: ['fall', 'winter'], priceTier: 3,
    vibeTags: ['architectural', 'native', 'dried', 'strange'],
    blurb: 'A cylinder of thousands of hooked filaments in tight rows. Australian, alien-looking, and effectively permanent once dried.',
  },
  {
    id: 'hellebore',
    commonName: 'Hellebore',
    scientificName: 'Helleborus orientalis',
    query: 'Helleborus orientalis flower',
    colors: [
      { name: 'sage green', hex: '#B3BE96' }, { name: 'plum', hex: '#6E4260' },
      { name: 'dusty rose', hex: '#CE95A0' }, { name: 'cream', hex: '#F0E9D6' },
    ],
    form: 'single', scale: 'secondary', scent: 'none',
    seasons: ['winter', 'spring'], priceTier: 3,
    vibeTags: ['moody', 'muted', 'nodding', 'sophisticated'],
    blurb: 'Faces downward and flowers in the cold, in colours that all look slightly dusty. The most grown-up flower on this list.',
  },
  {
    id: 'camellia',
    commonName: 'Camellia',
    scientificName: 'Camellia japonica',
    query: 'Camellia japonica flower',
    colors: [
      { name: 'white', hex: '#F6F2E9' }, { name: 'blush', hex: '#F0BFC7' },
      { name: 'crimson', hex: '#A81E33' },
    ],
    form: 'ruffled', scale: 'focal', scent: 'light',
    seasons: ['winter', 'spring'], priceTier: 2,
    vibeTags: ['formal', 'glossy', 'symmetrical', 'heirloom'],
    blurb: 'Petals arranged in near-perfect concentric rings against very dark glossy leaves. Drops the whole flower at once when done.',
  },
  {
    id: 'cherry-blossom',
    commonName: 'Cherry Blossom',
    scientificName: 'Prunus serrulata',
    query: 'Prunus serrulata flower branch',
    colors: [
      { name: 'pale pink', hex: '#F4D2DA' }, { name: 'white', hex: '#F7F3EB' },
    ],
    form: 'cluster', scale: 'focal', scent: 'light',
    seasons: ['spring'], priceTier: 2,
    vibeTags: ['branch', 'airy', 'sculptural', 'fleeting'],
    blurb: 'Sold as a bare branch that opens indoors over a week. Gives an arrangement height and negative space at the same time.',
  },
  {
    id: 'lilac',
    commonName: 'Lilac',
    scientificName: 'Syringa vulgaris',
    query: 'Syringa vulgaris flower',
    colors: [
      { name: 'lilac', hex: '#B49AD0' }, { name: 'white', hex: '#F5F1E8' },
      { name: 'deep purple', hex: '#5A3E84' },
    ],
    form: 'cluster', scale: 'focal', scent: 'sweet',
    seasons: ['spring'], priceTier: 2,
    vibeTags: ['perfumed', 'nostalgic', 'abundant', 'branch'],
    blurb: 'Enormous scented cones on a woody stem. Wilts fast unless the stem end is split, and is worth the trouble for about five days.',
  },
  {
    id: 'gardenia',
    commonName: 'Gardenia',
    scientificName: 'Gardenia jasminoides',
    query: 'Gardenia jasminoides flower',
    colors: [{ name: 'ivory', hex: '#F5EFDF' }],
    form: 'ruffled', scale: 'focal', scent: 'sweet',
    seasons: ['summer'], priceTier: 3,
    vibeTags: ['perfumed', 'bridal', 'waxy', 'luxurious'],
    blurb: 'Thick waxy white petals that bruise brown if you touch them. The scent is enormous and unmistakable.',
  },
  {
    id: 'clematis',
    commonName: 'Clematis',
    scientificName: 'Clematis hybrida',
    query: 'Clematis flower',
    colors: [
      { name: 'violet', hex: '#6D51A2' }, { name: 'white', hex: '#F4F1E8' },
      { name: 'mauve', hex: '#B389B8' },
    ],
    form: 'star', scale: 'secondary', scent: 'light',
    seasons: ['spring', 'summer'], priceTier: 2,
    vibeTags: ['vining', 'flat-faced', 'movement', 'romantic'],
    blurb: 'Comes on a trailing vine, so it drapes over the edge of a vase instead of standing up in it.',
  },
  {
    id: 'sea-holly',
    commonName: 'Sea Holly',
    scientificName: 'Eryngium planum',
    query: 'Eryngium planum flower',
    colors: [
      { name: 'steel blue', hex: '#6E85A8' }, { name: 'silver', hex: '#B9BFB8' },
    ],
    form: 'spiky', scale: 'secondary', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 2,
    vibeTags: ['metallic', 'thistle', 'architectural', 'cool'],
    blurb: 'Cone and collar both stiff, spined, and a metallic blue that looks almost painted on. Sharp — literally.',
  },
  {
    id: 'globe-thistle',
    commonName: 'Globe Thistle',
    scientificName: 'Echinops ritro',
    query: 'Echinops ritro flower',
    colors: [
      { name: 'steel blue', hex: '#7488AE' }, { name: 'silver', hex: '#BCC1BA' },
    ],
    form: 'globe', scale: 'secondary', scent: 'none',
    seasons: ['summer'], priceTier: 2,
    vibeTags: ['geometric', 'spiky', 'cool', 'dried'],
    blurb: 'A perfect steel-blue sphere bristling all over. Half geometry lesson, half weapon.',
  },
  {
    id: 'tuberose',
    commonName: 'Tuberose',
    scientificName: 'Agave amica',
    query: 'Polianthes tuberosa flower',
    colors: [{ name: 'ivory', hex: '#F5F0E1' }],
    form: 'cluster', scale: 'secondary', scent: 'sweet',
    seasons: ['summer', 'fall'], priceTier: 3,
    vibeTags: ['perfumed', 'narcotic', 'bridal', 'luxurious'],
    blurb: 'Waxy white flowers up a tall spike with a scent so heavy it is used as a perfume base note on its own.',
  },
  {
    id: 'dendrobium-orchid',
    commonName: 'Dendrobium Orchid',
    scientificName: 'Dendrobium phalaenopsis',
    query: 'Dendrobium orchid flower',
    colors: [
      { name: 'white', hex: '#F5F2E9' }, { name: 'magenta', hex: '#B93C7E' },
      { name: 'lime', hex: '#BFCC70' },
    ],
    form: 'star', scale: 'focal', scent: 'none',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 3,
    vibeTags: ['tropical', 'exotic', 'arching', 'modern'],
    blurb: 'A dozen flat faces marching up an arching stem. Lasts two to three weeks, which is unusual for something this delicate-looking.',
  },
  {
    id: 'cymbidium-orchid',
    commonName: 'Cymbidium Orchid',
    scientificName: 'Cymbidium hybridum',
    query: 'Cymbidium orchid flower',
    colors: [
      { name: 'chartreuse', hex: '#C3CD79' }, { name: 'cream', hex: '#F2EAD6' },
      { name: 'burgundy', hex: '#7B2438' }, { name: 'blush', hex: '#EEC4C8' },
    ],
    form: 'star', scale: 'focal', scent: 'light',
    seasons: ['winter', 'spring'], priceTier: 3,
    vibeTags: ['luxurious', 'waxy', 'exotic', 'formal'],
    blurb: 'Thick waxy blooms the size of a palm, often in greens and browns you would not expect from an orchid.',
  },
  {
    id: 'bouvardia',
    commonName: 'Bouvardia',
    scientificName: 'Bouvardia longiflora',
    query: 'Bouvardia flower',
    colors: [
      { name: 'white', hex: '#F5F2E9' }, { name: 'blush', hex: '#F0C4C9' },
      { name: 'coral', hex: '#EE8877' },
    ],
    form: 'cluster', scale: 'secondary', scent: 'sweet',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 2,
    vibeTags: ['starry', 'clustered', 'perfumed', 'refined'],
    blurb: 'Clusters of narrow four-pointed tubes. Fine-textured enough to soften the edge between a big focal flower and greenery.',
  },
  {
    id: 'shasta-daisy',
    commonName: 'Shasta Daisy',
    scientificName: 'Leucanthemum superbum',
    query: 'Leucanthemum superbum flower',
    colors: [{ name: 'white', hex: '#F6F3EB' }, { name: 'gold centre', hex: '#EFC02A' }],
    form: 'single', scale: 'secondary', scent: 'light',
    seasons: ['spring', 'summer'], priceTier: 1,
    vibeTags: ['simple', 'fresh', 'classic', 'cheerful'],
    blurb: 'The flower a child draws. White ray petals, gold centre, no complications whatsoever.',
  },
  {
    id: 'gloriosa-lily',
    commonName: 'Gloriosa Lily',
    scientificName: 'Gloriosa superba',
    query: 'Gloriosa superba flower',
    colors: [
      { name: 'flame red', hex: '#C6302B' }, { name: 'gold', hex: '#EEB528' },
    ],
    form: 'star', scale: 'focal', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 3,
    vibeTags: ['flame', 'exotic', 'dramatic', 'movement'],
    blurb: 'Petals swept fully backward with wavy edges, red fading to gold. Looks mid-motion even sitting still.',
  },
  {
    id: 'nerine',
    commonName: 'Nerine',
    scientificName: 'Nerine bowdenii',
    query: 'Nerine bowdenii flower',
    colors: [
      { name: 'hot pink', hex: '#E2559A' }, { name: 'white', hex: '#F4F1E8' },
    ],
    form: 'star', scale: 'secondary', scent: 'none',
    seasons: ['fall'], priceTier: 2,
    vibeTags: ['sparkling', 'late-season', 'fine', 'jewel-like'],
    blurb: 'Narrow curling petals that catch light like they have glitter in them, which is an actual property of the cell structure.',
  },
  {
    id: 'agapanthus',
    commonName: 'Agapanthus',
    scientificName: 'Agapanthus africanus',
    query: 'Agapanthus africanus flower',
    colors: [
      { name: 'periwinkle', hex: '#8296CE' }, { name: 'white', hex: '#F4F1E8' },
      { name: 'deep blue', hex: '#3F55A0' },
    ],
    form: 'globe', scale: 'focal', scent: 'none',
    seasons: ['summer'], priceTier: 2,
    vibeTags: ['architectural', 'airy', 'blue', 'tall'],
    blurb: 'An exploding sphere of trumpets on a bare stem — the airy, open version of what an allium does densely.',
  },
  {
    id: 'phlox',
    commonName: 'Garden Phlox',
    scientificName: 'Phlox paniculata',
    query: 'Phlox paniculata flower',
    colors: [
      { name: 'white', hex: '#F5F2E9' }, { name: 'blush', hex: '#EFBFCC' },
      { name: 'magenta', hex: '#C2447F' },
    ],
    form: 'cluster', scale: 'secondary', scent: 'sweet',
    seasons: ['summer'], priceTier: 1,
    vibeTags: ['cottage', 'perfumed', 'domed', 'nostalgic'],
    blurb: 'Domed heads of flat five-petalled flowers, often with a contrasting eye. Smells like the middle of July.',
  },
  {
    id: 'pincushion-protea',
    commonName: 'Pincushion Protea',
    scientificName: 'Leucospermum cordifolium',
    query: 'Leucospermum cordifolium flower',
    colors: [
      { name: 'tangerine', hex: '#EE8226' }, { name: 'coral', hex: '#EF6D4E' },
      { name: 'gold', hex: '#EDB92C' },
    ],
    form: 'spiky', scale: 'focal', scent: 'none',
    seasons: ['winter', 'spring'], priceTier: 3,
    vibeTags: ['fireworks', 'sculptural', 'tropical', 'bold'],
    blurb: 'A dome of curved styles shooting outward like a frozen firework. Structural enough to carry an arrangement alone.',
  },
  {
    id: 'stephanotis',
    commonName: 'Stephanotis',
    scientificName: 'Stephanotis floribunda',
    query: 'Stephanotis floribunda flower',
    colors: [{ name: 'white', hex: '#F6F3EB' }],
    form: 'star', scale: 'secondary', scent: 'sweet',
    seasons: ['spring', 'summer'], priceTier: 3,
    vibeTags: ['bridal', 'waxy', 'perfumed', 'traditional'],
    blurb: 'Small waxy white trumpets, traditionally wired individually into bridal work. Heavy jasmine scent.',
  },
  {
    id: 'ornamental-allium-drumstick',
    commonName: 'Drumstick Allium',
    scientificName: 'Allium sphaerocephalon',
    query: 'Allium sphaerocephalon flower',
    colors: [
      { name: 'wine', hex: '#7C2F4E' }, { name: 'green', hex: '#9FAF7A' },
    ],
    form: 'globe', scale: 'secondary', scent: 'spicy',
    seasons: ['summer'], priceTier: 2,
    vibeTags: ['egg-shaped', 'modern', 'wine', 'movement'],
    blurb: 'A small egg-shaped head that ripens from green to wine, on a stem that bends wherever it likes.',
  },
  {
    id: 'ammi-visnaga',
    commonName: 'Green Mist Ammi',
    scientificName: 'Ammi visnaga',
    query: 'Ammi visnaga flower',
    colors: [
      { name: 'chartreuse', hex: '#C4CE84' }, { name: 'cream', hex: '#F0E9D5' },
    ],
    form: 'cluster', scale: 'secondary', scent: 'green',
    seasons: ['summer'], priceTier: 1,
    vibeTags: ['airy', 'lacy', 'green', 'meadow'],
    blurb: 'Domed lace-caps in a green so pale it goes cream at the edges. Softens hard-edged flowers better than any greenery.',
  },
  {
    id: 'garden-rose-spray',
    commonName: 'Spray Rose',
    scientificName: 'Rosa hybrida spray',
    query: 'spray rose Rosa flower cluster',
    colors: [
      { name: 'blush', hex: '#EEC0C6' }, { name: 'cream', hex: '#F4EBD9' },
      { name: 'peach', hex: '#F3B48F' }, { name: 'wine', hex: '#7C2438' },
    ],
    form: 'ruffled', scale: 'secondary', scent: 'light',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 2,
    vibeTags: ['clustered', 'romantic', 'small-scale', 'versatile'],
    blurb: 'Five or six small roses per stem instead of one large one. Fills the gap between a focal rose and a filler.',
  },
  {
    id: 'japanese-anemone',
    commonName: 'Japanese Anemone',
    scientificName: 'Eriocapitella hupehensis',
    query: 'Anemone hupehensis flower',
    colors: [
      { name: 'pale pink', hex: '#EFC8D0' }, { name: 'white', hex: '#F6F3EA' },
    ],
    form: 'single', scale: 'secondary', scent: 'none',
    seasons: ['fall'], priceTier: 2,
    vibeTags: ['airy', 'nodding', 'late-season', 'delicate'],
    blurb: 'Simple open faces on tall wiry stems that never stop moving. Nothing like the bold coronaria anemone despite the name.',
  },
  {
    id: 'coral-charm-peony',
    commonName: 'Coral Charm Peony',
    scientificName: 'Paeonia Coral Charm',
    query: 'Paeonia Coral Charm flower',
    colors: [
      { name: 'coral', hex: '#F28B6B' }, { name: 'peach', hex: '#F5BC93' },
    ],
    form: 'ruffled', scale: 'focal', scent: 'sweet',
    seasons: ['spring', 'summer'], priceTier: 3,
    vibeTags: ['coral', 'fading', 'luxurious', 'painterly'],
    blurb: 'Opens deep coral and fades to peach then near-cream over four days, so the same stem is three colours across its life.',
  },
  {
    id: 'magnolia',
    commonName: 'Magnolia',
    scientificName: 'Magnolia grandiflora',
    query: 'Magnolia grandiflora flower',
    colors: [{ name: 'ivory', hex: '#F4EEDC' }, { name: 'blush', hex: '#EFC9CC' }],
    form: 'bell', scale: 'focal', scent: 'sweet',
    seasons: ['spring', 'summer'], priceTier: 3,
    vibeTags: ['branch', 'sculptural', 'waxy', 'statement'],
    blurb: 'Sold as a cut branch with leaves like polished leather. One stem is an entire arrangement.',
  },
  {
    id: 'hollyhock',
    commonName: 'Hollyhock',
    scientificName: 'Alcea rosea',
    query: 'Alcea rosea flower',
    colors: [
      { name: 'blush', hex: '#EFBFC9' }, { name: 'cream', hex: '#F3EAD6' },
      { name: 'wine', hex: '#6E2137' },
    ],
    form: 'bell', scale: 'focal', scent: 'none',
    seasons: ['summer'], priceTier: 2,
    vibeTags: ['cottage', 'tall', 'vertical', 'nostalgic'],
    blurb: 'A two-metre spire of crepe-paper saucers opening bottom to top. Pure cottage garden.',
  },
  {
    id: 'lotus',
    commonName: 'Lotus',
    scientificName: 'Nelumbo nucifera',
    query: 'Nelumbo nucifera flower',
    colors: [{ name: 'blush', hex: '#F1C4CC' }, { name: 'cream', hex: '#F5EEDE' }],
    form: 'ruffled', scale: 'focal', scent: 'sweet',
    seasons: ['summer'], priceTier: 3,
    vibeTags: ['sculptural', 'serene', 'statement', 'unusual'],
    blurb: 'Enormous cupped petals on a bare stem. The seed pods left behind are a florist staple in their own right.',
  },
  {
    id: 'wisteria',
    commonName: 'Wisteria',
    scientificName: 'Wisteria sinensis',
    query: 'Wisteria sinensis flower',
    colors: [{ name: 'lilac', hex: '#B3A0D2' }, { name: 'white', hex: '#F4F1E8' }],
    form: 'cluster', scale: 'focal', scent: 'sweet',
    seasons: ['spring'], priceTier: 3,
    vibeTags: ['cascading', 'perfumed', 'dramatic', 'branch'],
    blurb: 'Long scented racemes that hang straight down. Cut branches last only days, which is rather the point.',
  },
  {
    id: 'rhododendron',
    commonName: 'Rhododendron',
    scientificName: 'Rhododendron ponticum',
    query: 'Rhododendron flower truss',
    colors: [
      { name: 'mauve', hex: '#C08BC0' }, { name: 'blush', hex: '#EFC3CB' },
      { name: 'crimson', hex: '#A82238' },
    ],
    form: 'cluster', scale: 'focal', scent: 'light',
    seasons: ['spring'], priceTier: 2,
    vibeTags: ['branch', 'abundant', 'glossy', 'bold'],
    blurb: 'Great domed trusses on a woody branch, backed by dark evergreen leaves.',
  },
  {
    id: 'bleeding-heart',
    commonName: 'Bleeding Heart',
    scientificName: 'Lamprocapnos spectabilis',
    query: 'Lamprocapnos spectabilis flower',
    colors: [{ name: 'rose', hex: '#E38AA8' }, { name: 'white', hex: '#F5F2E9' }],
    form: 'bell', scale: 'secondary', scent: 'none',
    seasons: ['spring'], priceTier: 2,
    vibeTags: ['arching', 'whimsical', 'delicate', 'storybook'],
    blurb: 'A row of little lockets strung along an arching stem. Nothing else in a spring bouquet looks like it.',
  },
  {
    id: 'columbine',
    commonName: 'Columbine',
    scientificName: 'Aquilegia vulgaris',
    query: 'Aquilegia vulgaris flower',
    colors: [
      { name: 'violet', hex: '#6B52A0' }, { name: 'blush', hex: '#EFC4CE' },
      { name: 'cream', hex: '#F3EBD9' },
    ],
    form: 'bell', scale: 'secondary', scent: 'none',
    seasons: ['spring'], priceTier: 2,
    vibeTags: ['spurred', 'nodding', 'woodland', 'delicate'],
    blurb: 'Nodding bonnets with long backward spurs, on stems fine enough to tremble.',
  },
  {
    id: 'calendula',
    commonName: 'Calendula',
    scientificName: 'Calendula officinalis',
    query: 'Calendula officinalis flower',
    colors: [{ name: 'marigold gold', hex: '#EFA92A' }, { name: 'apricot', hex: '#F1B172' }],
    form: 'single', scale: 'secondary', scent: 'green',
    seasons: ['spring', 'fall'], priceTier: 1,
    vibeTags: ['cheerful', 'cottage', 'edible', 'warm'],
    blurb: 'Flat gold discs on sticky, resinous stems that smell sharply green when you cut them.',
  },
  {
    id: 'coreopsis',
    commonName: 'Coreopsis',
    scientificName: 'Coreopsis lanceolata',
    query: 'Coreopsis lanceolata flower',
    colors: [{ name: 'gold', hex: '#EFC12C' }, { name: 'rust', hex: '#B4552A' }],
    form: 'single', scale: 'secondary', scent: 'none',
    seasons: ['summer'], priceTier: 1,
    vibeTags: ['prairie', 'cheerful', 'fine-stemmed', 'meadow'],
    blurb: 'Small gold daisies with fringed tips, held high on wiry stems that move in any draught.',
  },
  {
    id: 'salvia',
    commonName: 'Salvia',
    scientificName: 'Salvia nemorosa',
    query: 'Salvia nemorosa flower',
    colors: [{ name: 'violet', hex: '#5F4A96' }, { name: 'rose', hex: '#DA87A6' }],
    form: 'spiky', scale: 'secondary', scent: 'green',
    seasons: ['summer'], priceTier: 1,
    vibeTags: ['vertical', 'meadow', 'aromatic', 'fine'],
    blurb: 'Dense violet spires on square stems that smell herbal when handled. Reliable vertical line.',
  },
  {
    id: 'heliotrope',
    commonName: 'Heliotrope',
    scientificName: 'Heliotropium arborescens',
    query: 'Heliotropium arborescens flower',
    colors: [{ name: 'deep purple', hex: '#553A7E' }, { name: 'white', hex: '#F4F1E8' }],
    form: 'cluster', scale: 'secondary', scent: 'sweet',
    seasons: ['summer'], priceTier: 2,
    vibeTags: ['perfumed', 'velvety', 'antique', 'dense'],
    blurb: 'Flat heads of tiny purple flowers that smell strongly of vanilla and cherry pie.',
  },
  {
    id: 'strawflower',
    commonName: 'Strawflower',
    scientificName: 'Xerochrysum bracteatum',
    query: 'Xerochrysum bracteatum flower',
    colors: [
      { name: 'gold', hex: '#EFB92B' }, { name: 'blush', hex: '#EFC2C8' },
      { name: 'rust', hex: '#B4592C' }, { name: 'cream', hex: '#F2EAD7' },
    ],
    form: 'globe', scale: 'secondary', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 1,
    vibeTags: ['papery', 'dried', 'crisp', 'everlasting'],
    blurb: 'The bracts are genuinely papery and rustle when touched. Dries without changing at all.',
  },
  {
    id: 'tithonia',
    commonName: 'Mexican Sunflower',
    scientificName: 'Tithonia rotundifolia',
    query: 'Tithonia rotundifolia flower',
    colors: [{ name: 'tangerine', hex: '#EE6B22' }, { name: 'scarlet', hex: '#CE3822' }],
    form: 'single', scale: 'secondary', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 1,
    vibeTags: ['saturated', 'warm', 'bold', 'late-summer'],
    blurb: 'A velvety orange disc on a hollow stem that has to be handled carefully — it bends where you grip it.',
  },
  {
    id: 'wallflower',
    commonName: 'Wallflower',
    scientificName: 'Erysimum cheiri',
    query: 'Erysimum cheiri flower',
    colors: [
      { name: 'rust', hex: '#B4592B' }, { name: 'gold', hex: '#EBAF2A' },
      { name: 'plum', hex: '#6C3C63' },
    ],
    form: 'cluster', scale: 'secondary', scent: 'sweet',
    seasons: ['spring'], priceTier: 1,
    vibeTags: ['perfumed', 'velvety', 'antique', 'warm'],
    blurb: 'Clusters in scorched oranges and browns, with a scent somewhere between violet and clove.',
  },
  {
    id: 'snowdrop',
    commonName: 'Snowdrop',
    scientificName: 'Galanthus nivalis',
    query: 'Galanthus nivalis flower',
    colors: [{ name: 'white', hex: '#F6F3EB' }],
    form: 'bell', scale: 'secondary', scent: 'light',
    seasons: ['winter'], priceTier: 2,
    vibeTags: ['tiny', 'first-of-the-year', 'delicate', 'nodding'],
    blurb: 'The first thing to flower, often through frost. Sold in small tied posies rather than by the stem.',
  },
  {
    id: 'bluebell',
    commonName: 'Bluebell',
    scientificName: 'Hyacinthoides hispanica',
    query: 'Hyacinthoides hispanica flower',
    colors: [{ name: 'periwinkle', hex: '#8B9CD6' }, { name: 'white', hex: '#F4F1E8' }],
    form: 'bell', scale: 'secondary', scent: 'light',
    seasons: ['spring'], priceTier: 1,
    vibeTags: ['woodland', 'nodding', 'blue', 'wild'],
    blurb: 'Nodding bells up one side of an arching stem. The cultivated Spanish kind, not the protected native.',
  },
  {
    id: 'sweet-violet',
    commonName: 'Sweet Violet',
    scientificName: 'Viola odorata',
    query: 'Viola odorata flower',
    colors: [{ name: 'violet', hex: '#5F4593' }, { name: 'white', hex: '#F4F1E8' }],
    form: 'single', scale: 'secondary', scent: 'sweet',
    seasons: ['winter', 'spring'], priceTier: 2,
    vibeTags: ['tiny', 'perfumed', 'nostalgic', 'posy'],
    blurb: 'Sold in tight nosegays with their own leaves as a collar. The scent famously switches itself off as you smell it.',
  },
];

export const FILLERS = [
  {
    id: 'eucalyptus-silver-dollar',
    commonName: 'Silver Dollar Eucalyptus',
    scientificName: 'Eucalyptus cinerea',
    query: 'Eucalyptus cinerea leaves',
    colors: [{ name: 'silver green', hex: '#A9B8A4' }],
    form: 'cluster', scale: 'filler', scent: 'green',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 1,
    vibeTags: ['silvery', 'draping', 'modern', 'aromatic', 'airy'],
    blurb: 'Round coin-shaped leaves in a dusty blue-green, on stems that drape. The default greenery of the last decade for good reason.',
  },
  {
    id: 'eucalyptus-seeded',
    commonName: 'Seeded Eucalyptus',
    scientificName: 'Eucalyptus polyanthemos',
    query: 'Eucalyptus polyanthemos foliage',
    colors: [{ name: 'grey green', hex: '#96A48F' }],
    form: 'cluster', scale: 'filler', scent: 'green',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 1,
    vibeTags: ['textural', 'draping', 'rustic', 'aromatic', 'dense'],
    blurb: 'Narrower leaves plus clusters of small hard seed pods, which is most of the texture. Heavier and wilder than silver dollar.',
  },
  {
    id: 'italian-ruscus',
    commonName: 'Italian Ruscus',
    scientificName: 'Ruscus aculeatus',
    query: 'Ruscus aculeatus foliage',
    colors: [{ name: 'deep green', hex: '#3E6B45' }],
    form: 'spiky', scale: 'filler', scent: 'none',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 1,
    vibeTags: ['glossy', 'structured', 'classic', 'dense'],
    blurb: 'Stiff arching stems of small pointed glossy leaves. The workhorse green that holds a shape without drawing attention.',
  },
  {
    id: 'babys-breath',
    commonName: "Baby's Breath",
    scientificName: 'Gypsophila paniculata',
    query: 'Gypsophila paniculata flower',
    colors: [{ name: 'white', hex: '#F4F1E8' }],
    form: 'cluster', scale: 'filler', scent: 'light',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 1,
    vibeTags: ['cloud', 'airy', 'nostalgic', 'white'],
    blurb: 'A cloud of pinhead flowers. Out of fashion as a filler and back in fashion by the armful on its own.',
  },
  {
    id: 'bupleurum',
    commonName: 'Bupleurum',
    scientificName: 'Bupleurum rotundifolium',
    query: 'Bupleurum rotundifolium plant',
    colors: [{ name: 'chartreuse', hex: '#B7C56B' }],
    form: 'cluster', scale: 'filler', scent: 'green',
    seasons: ['spring', 'summer', 'fall'], priceTier: 1,
    vibeTags: ['acid-green', 'airy', 'modern', 'light'],
    blurb: 'Acid-green bracts on branching stems. The only filler that adds brightness rather than just filling gaps.',
  },
  {
    id: 'dusty-miller',
    commonName: 'Dusty Miller',
    scientificName: 'Jacobaea maritima',
    query: 'Jacobaea maritima leaves',
    colors: [{ name: 'silver', hex: '#C3C6BA' }],
    form: 'cluster', scale: 'filler', scent: 'green',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 1,
    vibeTags: ['velvet', 'silver', 'muted', 'soft', 'dense'],
    blurb: 'Felted silver leaves cut like lace. Turns down the volume on anything saturated sitting next to it.',
  },
  {
    id: 'astilbe',
    commonName: 'Astilbe',
    scientificName: 'Astilbe arendsii',
    query: 'Astilbe arendsii flower',
    colors: [
      { name: 'blush', hex: '#EFC2CB' }, { name: 'cream', hex: '#F2EAD8' },
      { name: 'raspberry', hex: '#B94667' },
    ],
    form: 'spiky', scale: 'filler', scent: 'light',
    seasons: ['spring', 'summer'], priceTier: 2,
    vibeTags: ['feathery', 'plume', 'soft', 'romantic', 'airy'],
    blurb: 'Feathered plumes that read as smoke rather than flower. Adds softness and height at the same time, which is rare.',
  },
  {
    id: 'leatherleaf-fern',
    commonName: 'Leatherleaf Fern',
    scientificName: 'Rumohra adiantiformis',
    query: 'Rumohra adiantiformis frond',
    colors: [{ name: 'forest green', hex: '#37613C' }],
    form: 'spiky', scale: 'filler', scent: 'none',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 1,
    vibeTags: ['classic', 'dense', 'traditional', 'flat'],
    blurb: 'The dark triangular frond behind every supermarket bunch. Cheap, sturdy, and slightly old-fashioned in a way that can work.',
  },
  {
    id: 'olive-branch',
    commonName: 'Olive Branch',
    scientificName: 'Olea europaea',
    query: 'Olea europaea branch leaves',
    colors: [{ name: 'grey green', hex: '#8E9C7C' }],
    form: 'spiky', scale: 'filler', scent: 'green',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 2,
    vibeTags: ['mediterranean', 'silvery', 'linear', 'airy'],
    blurb: 'Narrow leaves, silver underneath and green on top, so the whole branch shimmers when it moves.',
  },
  {
    id: 'pittosporum',
    commonName: 'Pittosporum',
    scientificName: 'Pittosporum tenuifolium',
    query: 'Pittosporum tenuifolium leaves',
    colors: [{ name: 'variegated green', hex: '#8FA283' }],
    form: 'cluster', scale: 'filler', scent: 'green',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 1,
    vibeTags: ['wavy', 'dense', 'variegated', 'compact'],
    blurb: 'Wavy-edged leaves on near-black stems, whorled tightly enough to fill a hole on their own.',
  },
  {
    id: 'salal',
    commonName: 'Salal',
    scientificName: 'Gaultheria shallon',
    query: 'Gaultheria shallon leaves',
    colors: [{ name: 'deep green', hex: '#3F6640' }],
    form: 'cluster', scale: 'filler', scent: 'none',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 1,
    vibeTags: ['broad', 'glossy', 'dense', 'collar'],
    blurb: 'Broad leathery leaves used as a collar around the outside of a hand-tied bunch. Structural rather than decorative.',
  },
  {
    id: 'myrtle',
    commonName: 'Myrtle',
    scientificName: 'Myrtus communis',
    query: 'Myrtus communis leaves',
    colors: [{ name: 'deep green', hex: '#39623F' }],
    form: 'cluster', scale: 'filler', scent: 'green',
    seasons: ['spring', 'summer', 'fall', 'winter'], priceTier: 2,
    vibeTags: ['aromatic', 'fine', 'traditional', 'bridal'],
    blurb: 'Small dark aromatic leaves, traditionally included in royal wedding bouquets. Fine enough to disappear into a mix.',
  },
  {
    id: 'hypericum',
    commonName: 'Hypericum Berry',
    scientificName: 'Hypericum androsaemum',
    query: 'Hypericum androsaemum berries',
    colors: [
      { name: 'coral', hex: '#E9705C' }, { name: 'cream', hex: '#F0E6D0' },
      { name: 'chocolate', hex: '#6B4230' },
    ],
    form: 'cluster', scale: 'filler', scent: 'none',
    seasons: ['summer', 'fall', 'winter'], priceTier: 1,
    vibeTags: ['berry', 'glossy', 'textural', 'dense', 'autumnal'],
    blurb: 'Clusters of glossy pointed berries. Adds a solid dot of colour where a flower would be too soft.',
  },
  {
    id: 'solidago',
    commonName: 'Goldenrod',
    scientificName: 'Solidago canadensis',
    query: 'Solidago canadensis flower',
    colors: [{ name: 'gold', hex: '#E8B92C' }],
    form: 'spiky', scale: 'filler', scent: 'light',
    seasons: ['summer', 'fall'], priceTier: 1,
    vibeTags: ['plume', 'gold', 'meadow', 'airy'],
    blurb: 'Arching gold plumes of tiny flowers. Unfairly blamed for hay fever — that is ragweed, flowering at the same time.',
  },
  {
    id: 'statice',
    commonName: 'Statice',
    scientificName: 'Limonium sinuatum',
    query: 'Limonium sinuatum flower',
    colors: [
      { name: 'violet', hex: '#6E5AA4' }, { name: 'white', hex: '#F2EFE6' },
      { name: 'apricot', hex: '#EFB07E' },
    ],
    form: 'cluster', scale: 'filler', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 1,
    vibeTags: ['papery', 'dried', 'crisp', 'dense'],
    blurb: 'Papery and already half-dry on the stem, so it holds colour for months after everything else is gone.',
  },
  {
    id: 'queen-annes-lace',
    commonName: "Queen Anne's Lace",
    scientificName: 'Ammi majus',
    query: 'Ammi majus flower',
    colors: [{ name: 'white', hex: '#F4F1E8' }],
    form: 'cluster', scale: 'filler', scent: 'green',
    seasons: ['spring', 'summer'], priceTier: 1,
    vibeTags: ['lace', 'airy', 'meadow', 'flat-topped', 'wild'],
    blurb: 'Flat white lace-caps on hollow stems. Makes a tight arrangement look like it was picked from a roadside.',
  },
  {
    id: 'waxflower',
    commonName: 'Waxflower',
    scientificName: 'Chamelaucium uncinatum',
    query: 'Chamelaucium uncinatum flower',
    colors: [
      { name: 'blush', hex: '#EFBFC8' }, { name: 'white', hex: '#F4F1E8' },
      { name: 'magenta', hex: '#C24A83' },
    ],
    form: 'star', scale: 'filler', scent: 'green',
    seasons: ['winter', 'spring'], priceTier: 1,
    vibeTags: ['needle-leaved', 'tiny', 'aromatic', 'airy', 'starry'],
    blurb: 'Needle-like leaves that smell of lemon when crushed, covered in small five-petalled stars.',
  },
  {
    id: 'amaranthus',
    commonName: 'Hanging Amaranthus',
    scientificName: 'Amaranthus caudatus',
    query: 'Amaranthus caudatus flower',
    colors: [
      { name: 'burgundy', hex: '#77243A' }, { name: 'chartreuse', hex: '#B9C46B' },
    ],
    form: 'spiky', scale: 'filler', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 2,
    vibeTags: ['cascading', 'dramatic', 'rope-like', 'textural'],
    blurb: 'Long velvety ropes that hang straight down. The only reliable way to make an arrangement spill over the edge.',
  },
  {
    id: 'panicum-grass',
    commonName: 'Panicum Grass',
    scientificName: 'Panicum virgatum',
    query: 'Panicum virgatum inflorescence',
    colors: [{ name: 'tawny', hex: '#C9AE7C' }, { name: 'green', hex: '#9BAA7A' }],
    form: 'spiky', scale: 'filler', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 1,
    vibeTags: ['grass', 'airy', 'movement', 'meadow', 'fine'],
    blurb: 'A haze of seed heads on hair-fine stems. Adds motion and almost no visual weight.',
  },
  {
    id: 'bunny-tail-grass',
    commonName: 'Bunny Tail Grass',
    scientificName: 'Lagurus ovatus',
    query: 'Lagurus ovatus',
    colors: [{ name: 'cream', hex: '#EFE6CE' }],
    form: 'globe', scale: 'filler', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 1,
    vibeTags: ['soft', 'playful', 'dried', 'tactile', 'airy'],
    blurb: 'Small fuzzy oval heads that are genuinely nice to touch. Dries perfectly and stays soft.',
  },
  {
    id: 'lavender',
    commonName: 'Lavender',
    scientificName: 'Lavandula angustifolia',
    query: 'Lavandula angustifolia flower',
    colors: [{ name: 'lavender', hex: '#8F82BE' }, { name: 'white', hex: '#F2EFE6' }],
    form: 'spiky', scale: 'filler', scent: 'sweet',
    seasons: ['summer'], priceTier: 1,
    vibeTags: ['aromatic', 'dried', 'silvery', 'airy', 'meadow'],
    blurb: 'Grey-green stems topped with scented violet spikes. Dries perfectly and keeps its smell for a year.',
  },
  {
    id: 'jasmine',
    commonName: 'Jasmine',
    scientificName: 'Jasminum polyanthum',
    query: 'Jasminum polyanthum flower',
    colors: [{ name: 'white', hex: '#F6F3EB' }, { name: 'blush', hex: '#F1CDD0' }],
    form: 'star', scale: 'filler', scent: 'sweet',
    seasons: ['winter', 'spring'], priceTier: 2,
    vibeTags: ['trailing', 'perfumed', 'starry', 'airy', 'delicate'],
    blurb: 'Trailing stems of small white stars opening from pink buds. The scent carries across a whole room.',
  },
  {
    id: 'verbena',
    commonName: 'Tall Verbena',
    scientificName: 'Verbena bonariensis',
    query: 'Verbena bonariensis flower',
    colors: [{ name: 'violet', hex: '#7A5AA6' }],
    form: 'cluster', scale: 'filler', scent: 'none',
    seasons: ['summer', 'fall'], priceTier: 1,
    vibeTags: ['airy', 'see-through', 'meadow', 'movement', 'fine'],
    blurb: 'Small violet clusters floating on tall bare stems. Adds height you can see straight through.',
  },
  {
    id: 'forget-me-not',
    commonName: 'Forget-Me-Not',
    scientificName: 'Myosotis sylvatica',
    query: 'Myosotis sylvatica flower',
    colors: [{ name: 'sky blue', hex: '#8FAEDA' }, { name: 'white', hex: '#F3F0E7' }],
    form: 'cluster', scale: 'filler', scent: 'none',
    seasons: ['spring'], priceTier: 1,
    vibeTags: ['tiny', 'blue', 'airy', 'woodland', 'delicate'],
    blurb: 'A haze of pinhead blue flowers with yellow eyes. Softens anything it is threaded through.',
  },
  {
    id: 'elderflower',
    commonName: 'Elderflower',
    scientificName: 'Sambucus nigra',
    query: 'Sambucus nigra flower',
    colors: [{ name: 'cream', hex: '#F2EBD6' }],
    form: 'cluster', scale: 'filler', scent: 'sweet',
    seasons: ['summer'], priceTier: 1,
    vibeTags: ['lace', 'flat-topped', 'wild', 'airy', 'hedgerow'],
    blurb: 'Broad creamy lace-caps on a hedgerow branch, with a heavy honeyed scent on a warm day.',
  },
  {
    id: 'honeysuckle',
    commonName: 'Honeysuckle',
    scientificName: 'Lonicera periclymenum',
    query: 'Lonicera periclymenum flower',
    colors: [{ name: 'cream', hex: '#F2EAD3' }, { name: 'apricot', hex: '#EFB07C' }],
    form: 'cluster', scale: 'filler', scent: 'sweet',
    seasons: ['summer'], priceTier: 2,
    vibeTags: ['trailing', 'perfumed', 'wild', 'hedgerow', 'airy'],
    blurb: 'Whorls of long curved trumpets on a trailing stem. Strongest scented at dusk.',
  },
  {
    id: 'winterberry',
    commonName: 'Winterberry',
    scientificName: 'Ilex verticillata',
    query: 'Ilex verticillata berries',
    colors: [{ name: 'scarlet', hex: '#B72026' }, { name: 'gold', hex: '#E0A32A' }],
    form: 'cluster', scale: 'filler', scent: 'none',
    seasons: ['fall', 'winter'], priceTier: 2,
    vibeTags: ['berry', 'bare-branch', 'graphic', 'dense', 'winter'],
    blurb: 'A leafless branch studded solid with red berries. The whole point is that there is no foliage at all.',
  },
  {
    id: 'daphne',
    commonName: 'Daphne',
    scientificName: 'Daphne odora',
    query: 'Daphne odora flower',
    colors: [{ name: 'blush', hex: '#EFC6CC' }, { name: 'white', hex: '#F4F1E8' }],
    form: 'cluster', scale: 'filler', scent: 'sweet',
    seasons: ['winter', 'spring'], priceTier: 2,
    vibeTags: ['perfumed', 'glossy', 'compact', 'dense', 'winter'],
    blurb: 'Small waxy clusters on glossy evergreen sprigs, with a scent out of all proportion to their size.',
  },
  {
    id: 'tansy',
    commonName: 'Tansy',
    scientificName: 'Tanacetum vulgare',
    query: 'Tanacetum vulgare flower',
    colors: [{ name: 'gold', hex: '#E5B326' }],
    form: 'cluster', scale: 'filler', scent: 'spicy',
    seasons: ['summer', 'fall'], priceTier: 1,
    vibeTags: ['button', 'flat-topped', 'dried', 'meadow', 'dense'],
    blurb: 'Flat clusters of gold buttons with no petals at all, over ferny aromatic leaves.',
  },
];
